# k8s/auth-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-service
    namespace: ecommerce
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-service
    template:
        metadata:
            labels:
                app: auth-service
        spec:
            containers:
                - name: auth
                  image: vatsalbhuva11/auth-service:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: JWT_SECRET
                        value: JIOj893j219da98hOJDJ
                      - name: PORT
                        value: "3000"
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "500m"
                      requests:
                          memory: "128Mi"
                          cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
    name: auth-service
    namespace: ecommerce
spec:
    selector:
        app: auth-service
    ports:
        - port: 3000
          targetPort: 3000
