# k8s/db-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: ecommerce
spec:
  selector:
    app: db-service
  ports:
    - port: 27017
      targetPort: 27017
